//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medical_Cards()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Id { get; set; }
        public int Number_Med_Card { get; set; }
        public int Number_Med_District { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Date_Birth { get; set; }
        public string Gender { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
        public Nullable<int> Entrance { get; set; }
        public int Flat { get; set; }
        public Nullable<int> Home_Phone_Number { get; set; }
        public int Mobile_Phone { get; set; }
        public string Place_Work { get; set; }
        public string Work_Address { get; set; }
        public string Position { get; set; }
        public Nullable<int> Work_Phone { get; set; }
        public string Note { get; set; }
        public int Shelving_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
