//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public int Number_Ticket { get; set; }
        public int Doctor_Id { get; set; }
        public int Cabinet_Number { get; set; }
        public System.DateTime Date_Time_Admission { get; set; }
        public int Med_Card_Id { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Medical_Cards Medical_Cards { get; set; }
    }
}
