//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Schedule
    {
        public int Id { get; set; }
        public Nullable<int> Number_Med_District { get; set; }
        public int Doctor_Id { get; set; }
        public Nullable<System.DateTime> Monday { get; set; }
        public Nullable<System.DateTime> Tuesday { get; set; }
        public Nullable<System.DateTime> Wednesday { get; set; }
        public Nullable<System.DateTime> Thursday { get; set; }
        public Nullable<System.DateTime> Friday { get; set; }
    
        public virtual Doctors Doctors { get; set; }
    }
}
