name: Docker 

on:
  push:
    branches: [master]
    tags: [v*.*.*]

env:
  DOCKER_BUILDKIT: 0  

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build \
            -f ./PolyclinicApp/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/polyclinicapp:${{ github.ref_name }} .
