name: Docker Build and Push

on:
  push:
    branches: [master]
    tags: [v*.*.*]

env:
  REPOSITORY: polyclinicapp
  BASE_IMAGE_TAG: 4.8-windowsservercore-ltsc2022
  DOCKER_BUILDKIT: "0"

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./PolyclinicApp
          file: ./PolyclinicApp/Dockerfile
          push: true
          platforms: windows/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:${{ github.ref_name }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
